package com.android.ootd.ui.map

import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performTextInput
import com.android.ootd.model.map.Location
import com.android.ootd.model.map.LocationRepository
import org.junit.Rule
import org.junit.Test

// Disclaimer: These tests were partly generated by AI and verified by humans

class LocationSelectionTest {
  @get:Rule val composeTestRule = createComposeRule()

  // Mock repository for testing
  private class MockLocationRepository : LocationRepository {
    override suspend fun search(query: String): List<Location> {
      return listOf(
          Location(name = "Test Location 1", latitude = 0.0, longitude = 0.0),
          Location(name = "Test Location 2", latitude = 0.0, longitude = 0.0))
    }

    override suspend fun reverseGeocode(latitude: Double, longitude: Double): Location {
      return Location(name = "Mock Location", latitude = latitude, longitude = longitude)
    }
  }

  // --- Location Selection Tag Tests ---
  @Test
  fun locationSelection_allEssentialTagsPresent() {
    composeTestRule.setContent {
      val vm = LocationSelectionViewModel()
      LocationSelectionSection(
          viewModel = vm, textGPSButton = "GPS", textLocationField = "Location", onGPSClick = {})
    }
    composeTestRule.onNodeWithTag(LocationSelectionTestTags.INPUT_LOCATION).assertIsDisplayed()
    composeTestRule.onNodeWithTag(LocationSelectionTestTags.LOCATION_GPS_BUTTON).assertIsDisplayed()
    composeTestRule
        .onNodeWithTag(LocationSelectionTestTags.LOCATION_DEFAULT_EPFL)
        .assertIsDisplayed()
  }

  @Test
  fun locationClearButton_appearsWhenTextEntered() {
    composeTestRule.setContent {
      val vm = LocationSelectionViewModel(MockLocationRepository())
      LocationSelectionSection(
          viewModel = vm, textGPSButton = "GPS", textLocationField = "Location", onGPSClick = {})
    }
    composeTestRule.onNodeWithTag(LocationSelectionTestTags.INPUT_LOCATION).performClick()
    composeTestRule.onNodeWithTag(LocationSelectionTestTags.INPUT_LOCATION).performTextInput("Test")
    // Wait for the loading state to complete (1000ms delay + processing time)
    composeTestRule.waitForIdle()
    Thread.sleep(1100)
    composeTestRule.waitForIdle()
    composeTestRule
        .onNodeWithTag(LocationSelectionTestTags.LOCATION_CLEAR_BUTTON)
        .assertIsDisplayed()
  }
}
