package com.android.ootd.ui.feed

import androidx.compose.ui.test.*
import androidx.compose.ui.test.junit4.createComposeRule
import com.android.ootd.model.posts.OutfitPost
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test

// DISCLAIMER: The following tests were partly generated by AI and verified by human.

class OutfitPostCardTest {

  @get:Rule val composeTestRule = createComposeRule()

  private fun setCard(
      post: OutfitPost,
      isBlurred: Boolean = false,
      isLiked: Boolean = false,
      likeCount: Int = 0,
      onLikeClick: (String) -> Unit = {},
      onSeeFitClick: (String) -> Unit = {}
  ) =
      composeTestRule.setContent {
        OutfitPostCard(
            post = post,
            isBlurred = isBlurred,
            isLiked = isLiked,
            likeCount = likeCount,
            onLikeClick = onLikeClick,
            onSeeFitClick = onSeeFitClick)
      }

  private fun n(tag: String) = composeTestRule.onNodeWithTag(tag)

  private fun post(
      name: String = "Test User",
      description: String = "Test description",
      profilePic: String = ""
  ) =
      OutfitPost(
          postUID = "id",
          ownerId = "owner",
          name = name,
          description = description,
          timestamp = 0L,
          outfitURL = "",
          userProfilePicURL = profilePic,
          itemsID = emptyList())

  @Test
  fun rendersBasics() {
    setCard(post("John Doe", "Casual Friday outfit"))

    n(OutfitPostCardTestTags.OUTFIT_POST_CARD).assertIsDisplayed()
    n(OutfitPostCardTestTags.POST_USERNAME).assertTextEquals("John Doe")
    n(OutfitPostCardTestTags.POST_DESCRIPTION).assertTextEquals("John Doe: Casual Friday outfit")
    n(OutfitPostCardTestTags.SEE_FIT_BUTTON).assertIsDisplayed().assertHasClickAction()

    // Like button + count should appear
    n(OutfitPostCardTestTags.LIKE_BUTTON).assertIsDisplayed()
    n(OutfitPostCardTestTags.LIKE_COUNT).assertIsDisplayed()
  }

  @Test
  fun rendersDescriptionLine_whenEmpty() {
    setCard(post(name = "Minimalist", description = ""))

    n(OutfitPostCardTestTags.POST_USERNAME).assertTextEquals("Minimalist")
    n(OutfitPostCardTestTags.POST_DESCRIPTION).assertTextEquals("Minimalist")
  }

  @Test
  fun seeFitButton_invokesCallback() {
    var clicks = 0
    var capturedPostUid = ""

    setCard(
        post(),
        onSeeFitClick = { uid ->
          clicks++
          capturedPostUid = uid
        })

    n(OutfitPostCardTestTags.SEE_FIT_BUTTON).performClick()

    assertEquals(1, clicks)
    assertEquals("id", capturedPostUid)
  }

  @Test
  fun renders_whenBlurred() {
    setCard(post(name = "Blurred"), isBlurred = true)
    n(OutfitPostCardTestTags.OUTFIT_POST_CARD).assertIsDisplayed()
  }

  @Test
  fun showsInitial_whenNoProfilePicture() {
    setCard(post(name = "Alex", description = "No pic", profilePic = ""))

    n(OutfitPostCardTestTags.PROFILE_INITIAL).assertIsDisplayed()
    n(OutfitPostCardTestTags.PROFILE_PIC).assertDoesNotExist()
  }

  @Test
  fun showsProfileImage_whenUrlProvided() {
    setCard(
        post(name = "Sophie", description = "With pic", profilePic = "https://example.com/pic.jpg"))

    n(OutfitPostCardTestTags.PROFILE_PIC).assertIsDisplayed()
    n(OutfitPostCardTestTags.PROFILE_INITIAL).assertDoesNotExist()
  }

  @Test
  fun description_expandsOnClick() {
    val longDesc = "Very long description ".repeat(20)
    val p = post(description = longDesc)

    setCard(p)

    val descNode = n(OutfitPostCardTestTags.POST_DESCRIPTION)
    descNode.performClick()
    descNode.assertIsDisplayed()
  }

  @Test
  fun showsRemainingLifetimeIndicator() {
    val recent = post().copy(timestamp = System.currentTimeMillis() - 2 * 60 * 60 * 1000)
    setCard(recent)

    n(OutfitPostCardTestTags.REMAINING_TIME).assertIsDisplayed()
  }

  @Test
  fun showsExpiredIndicator_forOldPost() {
    val old = post().copy(timestamp = System.currentTimeMillis() - 26 * 60 * 60 * 1000)
    setCard(old)

    n(OutfitPostCardTestTags.EXPIRED_INDICATOR).assertIsDisplayed()
  }

  @Test
  fun likeButton_showsCorrectCount() {
    setCard(post(), likeCount = 12)

    n(OutfitPostCardTestTags.LIKE_COUNT).assertTextEquals("12")
  }

  @Test
  fun likeButton_invokesCallback() {
    var clicks = 0

    setCard(post(), isLiked = false, likeCount = 0, onLikeClick = { clicks++ })

    n(OutfitPostCardTestTags.LIKE_BUTTON).performClick()

    assertEquals(1, clicks)
  }

  @Test
  fun likeButton_showsFilledHeart_whenLiked() {
    setCard(post(), isLiked = true)

    n(OutfitPostCardTestTags.LIKE_BUTTON).assertIsDisplayed()
    // Check contentDescription
    n(OutfitPostCardTestTags.LIKE_BUTTON).assertContentDescriptionEquals("Unlike")
  }

  @Test
  fun likeButton_showsEmptyHeart_whenNotLiked() {
    setCard(post(), isLiked = false)

    n(OutfitPostCardTestTags.LIKE_BUTTON).assertIsDisplayed()
    n(OutfitPostCardTestTags.LIKE_BUTTON).assertContentDescriptionEquals("Like")
  }
}
