package com.android.ootd.model.posts

import androidx.test.ext.junit.runners.AndroidJUnit4
import com.android.ootd.utils.FirebaseEmulator
import com.android.ootd.utils.FirestoreTest
import kotlinx.coroutines.tasks.await
import kotlinx.coroutines.test.runTest
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

// ACKNOWLEDGEMENT: These tests were partly generated by AI and verified by human.

@RunWith(AndroidJUnit4::class)
class LikesFirestoreRepositoryTest : FirestoreTest() {

  private lateinit var repo: LikesRepository

  @Before
  override fun setUp() {
    super.setUp()
    repo = likesRepository
  }

  private suspend fun createPost(ownerId: String): String {
    val postId = outfitPostRepository.getNewPostId()

    val post =
        OutfitPost(
            postUID = postId,
            ownerId = ownerId,
            name = "TestUser",
            userProfilePicURL = "",
            outfitURL = "fake.jpg",
            description = "",
            itemsID = emptyList(),
            timestamp = System.currentTimeMillis())

    outfitPostRepository.savePostToFirestore(post)
    return postId
  }

  @Test
  fun likePost_createsDocument() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val user = FirebaseEmulator.auth.currentUser!!.uid

    val postId = createPost(user)

    val like = Like(postId = postId, postLikerUserId = user, timestamp = System.currentTimeMillis())

    repo.likePost(like)

    val snap =
        FirebaseEmulator.firestore
            .collection(LIKE_COLLECTION_PATH)
            .document(postId)
            .collection("users")
            .document(user)
            .get()
            .await()

    assertTrue(snap.exists())
  }

  @Test
  fun unlikePost_deletesDocument() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val user = FirebaseEmulator.auth.currentUser!!.uid

    val postId = createPost(user)
    repo.likePost(Like(postId, user, System.currentTimeMillis()))
    repo.unlikePost(postId, user)

    val snap =
        FirebaseEmulator.firestore
            .collection(LIKE_COLLECTION_PATH)
            .document(postId)
            .collection("users")
            .document(user)
            .get()
            .await()

    assertFalse(snap.exists())
  }

  @Test
  fun isPostLikedByUser_returnsCorrectState() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val user = FirebaseEmulator.auth.currentUser!!.uid

    val postId = createPost(user)

    assertFalse(repo.isPostLikedByUser(postId, user))

    repo.likePost(Like(postId, user, System.currentTimeMillis()))

    assertTrue(repo.isPostLikedByUser(postId, user))
  }

  @Test
  fun getLikeCount_returnsCorrectValue() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val user = FirebaseEmulator.auth.currentUser!!.uid

    val postId = createPost(user)

    assertEquals(0, repo.getLikeCount(postId))

    repo.likePost(Like(postId, user, System.currentTimeMillis()))

    assertEquals(1, repo.getLikeCount(postId))
  }

  @Test
  fun getLikesForPost_returnsAllLikesForPost() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val userA = FirebaseEmulator.auth.currentUser!!.uid

    val postId = createPost(userA)

    repo.likePost(
        Like(postId = postId, postLikerUserId = userA, timestamp = System.currentTimeMillis()))

    val likes = repo.getLikesForPost(postId)

    assertEquals(1, likes.size)
    val like = likes.first()
    assertEquals(postId, like.postId)
    assertEquals(userA, like.postLikerUserId)
  }

  @Test
  fun isPostLikedByUser_returnsFalseOnError() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val userA = FirebaseEmulator.auth.currentUser!!.uid

    // invalid postId to trigger Firestore read error
    val result = repo.isPostLikedByUser("nonexistentPost", userA)

    assertFalse(result)
  }

  @Test
  fun likePost_throwsOnFirestoreFailure() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val uid = FirebaseEmulator.auth.currentUser!!.uid

    val invalidLike =
        Like(
            postId = "bad/id", // Firestore does not allow ids with '/'
            postLikerUserId = uid,
            timestamp = System.currentTimeMillis())

    assertThrows(Exception::class.java) { runTest { repo.likePost(invalidLike) } }
  }

  @Test
  fun unlikePost_throwsOnFirestoreFailure() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()
    val uid = FirebaseEmulator.auth.currentUser!!.uid

    assertThrows(Exception::class.java) { runTest { repo.unlikePost("bad/id", uid) } }
  }

  @Test
  fun getLikesForPost_returnsEmptyListOnError() = runTest {
    FirebaseEmulator.auth.signInAnonymously().await()

    val likes = repo.getLikesForPost("bad/id")

    assertTrue(likes.isEmpty())
  }
}
