package com.android.ootd.model.items

import junit.framework.TestCase
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Before
import org.junit.Test

// Test partially generated by the AI coding agent: Claude Sonnet 4.5
class ItemsRepositoryLocalTest {

  private lateinit var repository: ItemsRepositoryLocal

  @Before
  fun setup() {
    repository = ItemsRepositoryLocal()
    repository.clearAll()
  }

  val item1 =
      Item(
          itemUuid = "0",
          postUuids = listOf("post1"),
          image = ImageData("0", "https://example.com/image1.jpg"),
          category = "clothes",
          type = "t-shirt",
          brand = "Mango",
          price = 0.0,
          material = listOf(),
          link = "https://example.com/item1",
          ownerId = "user123")

  val item2 =
      Item(
          itemUuid = "1",
          postUuids = listOf("post1"),
          image = ImageData("1", "https://example.com/image1.jpg"),
          category = "shoes",
          type = "high heels",
          brand = "Zara",
          price = 30.0,
          material = listOf(),
          link = "https://example.com/item2",
          ownerId = "user123")

  val item3 =
      Item(
          itemUuid = "2",
          postUuids = listOf("post1"),
          image = ImageData("2", "https://example.com/image1.jpg"),
          category = "bags",
          type = "handbag",
          brand = "Vakko",
          price = 0.0,
          material = listOf(),
          link = "https://example.com/item3",
          ownerId = "user123")

  val item4 =
      Item(
          itemUuid = "3",
          postUuids = listOf("post1"),
          image = ImageData("4", "https://example.com/image1.jpg"),
          category = "accessories",
          type = "sunglasses",
          brand = "Ray-Ban",
          price = 100.0,
          material =
              listOf(
                  Material(name = "Plastic", percentage = 80.0),
                  Material(name = "Metal", percentage = 20.0)),
          link = "https://example.com/item4",
          ownerId = "user123")

  @Test
  fun getNewItemIdReturnsUniqueIDs() = runTest {
    val numberIDs = 100
    val uids = (0 until numberIDs).toSet().map { repository.getNewItemId() }.toSet()
    TestCase.assertEquals(uids.size, numberIDs)
  }

  @Test
  fun addItemWithTheCorrectID() = runTest {
    repository.addItem(item1)

    TestCase.assertEquals(1, repository.getItemCount())
    val storedItem = repository.getItemById(item1.itemUuid)
    TestCase.assertEquals(storedItem, item1)
  }

  @Test
  fun canAddItemToRepository() = runTest {
    repository.addItem(item1)
    TestCase.assertEquals(1, repository.getItemCount())
    val items = repository.getAllItems()

    TestCase.assertEquals(1, items.size)
    val expectedItem = item1.copy(itemUuid = "None", link = "None")
    val storedItem = items.first().copy(itemUuid = expectedItem.itemUuid, link = expectedItem.link)

    TestCase.assertEquals(expectedItem, storedItem)
  }

  @Test
  fun retrieveItemById() = runTest {
    repository.addItem(item1)
    repository.addItem(item2)
    repository.addItem(item3)
    TestCase.assertEquals(3, repository.getItemCount())

    val storedItem = repository.getItemById(item3.itemUuid)
    TestCase.assertEquals(storedItem, item3)

    val storedItem2 = repository.getItemById(item2.itemUuid)
    TestCase.assertEquals(storedItem2, item2)
  }

  @Test
  fun checkUidsAreUniqueInTheCollection() = runTest {
    val uid = "duplicate"
    val item1Modified = item1.copy(itemUuid = uid)
    val itemDuplicatedUID = item2.copy(itemUuid = uid)

    // Adding an item with an existing UID will overwrite the previous one
    repository.addItem(item1Modified)
    repository.addItem(itemDuplicatedUID)

    TestCase.assertEquals(1, repository.getItemCount())

    val items = repository.getAllItems()
    TestCase.assertEquals(items.size, 1)
    val storedItem = items.first()
    TestCase.assertEquals(storedItem.itemUuid, uid)
    // Should be the last added item (item2)
    TestCase.assertEquals(storedItem.brand, item2.brand)
  }

  @Test
  fun deleteItemById() = runTest {
    repository.addItem(item1)
    repository.addItem(item2)
    repository.addItem(item3)
    TestCase.assertEquals(3, repository.getItemCount())

    repository.deleteItem(item2.itemUuid)
    TestCase.assertEquals(2, repository.getItemCount())
    val items = repository.getAllItems()
    TestCase.assertEquals(items.size, 2)
    assert(!items.contains(item2))
    assert(items.contains(item1))
    assert(items.contains(item3))
  }

  @Test
  fun deleteNonExistingItemThrows() = runTest {
    repository.addItem(item1)
    repository.addItem(item3)
    TestCase.assertEquals(2, repository.getItemCount())

    // Deleting an item that does not exist should throw
    var didThrow = false
    try {
      repository.deleteItem(item2.itemUuid)
    } catch (e: Exception) {
      didThrow = true
      assert(e.message?.contains("Item not found") == true)
    }
    assert(didThrow)
    TestCase.assertEquals(2, repository.getItemCount())
  }

  @Test
  fun editItemById() = runTest {
    repository.addItem(item1)
    TestCase.assertEquals(1, repository.getItemCount())

    val newItem =
        item1.copy(
            type = "shirt",
            brand = "H&M",
            price = 20.0,
            material = listOf(Material(name = "Cotton", percentage = 100.0)))
    repository.editItem(item1.itemUuid, newItem)
    TestCase.assertEquals(1, repository.getItemCount())
    val items = repository.getAllItems()
    TestCase.assertEquals(items.size, 1)
    val storedItem = items.first()
    TestCase.assertEquals(storedItem, newItem)
  }

  @Test
  fun editNonExistingItemThrows() = runTest {
    repository.addItem(item1)
    TestCase.assertEquals(1, repository.getItemCount())

    // Editing an item that does not exist should throw
    val nonExistingItem = item2.copy(itemUuid = "nonExisting")
    var didThrow = false
    try {
      repository.editItem(nonExistingItem.itemUuid, nonExistingItem)
    } catch (e: Exception) {
      didThrow = true
      assert(e.message?.contains("Item not found") == true)
    }
    assert(didThrow)
    TestCase.assertEquals(1, repository.getItemCount())
  }

  @Test(expected = Exception::class)
  fun getItemByIdThrowsWhenItemNotFound() = runTest { repository.getItemById("nonExistingId") }

  @Test
  fun getAllItemsReturnsEmptyListWhenNoItems() = runTest {
    val items = repository.getAllItems()
    TestCase.assertEquals(0, items.size)
    TestCase.assertEquals(true, items.isEmpty())
  }

  @Test
  fun getAllItemsReturnsAllAddedItems() = runTest {
    repository.addItem(item1)
    repository.addItem(item2)
    repository.addItem(item3)
    repository.addItem(item4)

    val items = repository.getAllItems()
    TestCase.assertEquals(4, items.size)
    assert(items.contains(item1))
    assert(items.contains(item2))
    assert(items.contains(item3))
    assert(items.contains(item4))
  }

  @Test
  fun hasItemReturnsTrueForExistingItem() = runTest {
    repository.addItem(item1)

    assert(repository.hasItem(item1.itemUuid))
    assert(!repository.hasItem(item2.itemUuid))
  }

  @Test
  fun hasItemReturnsFalseForNonExistingItem() = runTest {
    assert(!repository.hasItem("nonExisting"))

    repository.addItem(item1)
    assert(!repository.hasItem("stillNonExisting"))
  }

  @Test
  fun clearAllRemovesAllItems() = runTest {
    repository.addItem(item1)
    repository.addItem(item2)
    repository.addItem(item3)
    TestCase.assertEquals(3, repository.getItemCount())

    repository.clearAll()

    TestCase.assertEquals(0, repository.getItemCount())
    val items = repository.getAllItems()
    assert(items.isEmpty())
    assert(!repository.hasItem(item1.itemUuid))
    assert(!repository.hasItem(item2.itemUuid))
    assert(!repository.hasItem(item3.itemUuid))
  }

  @Test
  fun getItemCountReturnsCorrectCount() = runTest {
    TestCase.assertEquals(0, repository.getItemCount())

    repository.addItem(item1)
    TestCase.assertEquals(1, repository.getItemCount())

    repository.addItem(item2)
    TestCase.assertEquals(2, repository.getItemCount())

    repository.addItem(item3)
    TestCase.assertEquals(3, repository.getItemCount())

    repository.deleteItem(item2.itemUuid)
    TestCase.assertEquals(2, repository.getItemCount())

    repository.clearAll()
    TestCase.assertEquals(0, repository.getItemCount())
  }

  @Test
  fun itemsWithComplexMaterialListAreStoredCorrectly() = runTest {
    repository.addItem(item4)

    val retrieved = repository.getItemById(item4.itemUuid)
    TestCase.assertEquals(item4, retrieved)
    TestCase.assertEquals(2, retrieved.material.size)
    TestCase.assertEquals("Plastic", retrieved.material[0]?.name)
    TestCase.assertEquals(80.0, retrieved.material[0]?.percentage)
    TestCase.assertEquals("Metal", retrieved.material[1]?.name)
    TestCase.assertEquals(20.0, retrieved.material[1]?.percentage)
  }

  @Test
  fun multipleOperationsInSequence() = runTest {
    // Add
    repository.addItem(item1)
    repository.addItem(item2)
    TestCase.assertEquals(2, repository.getItemCount())

    // Edit
    val modifiedItem1 = item1.copy(price = 50.0)
    repository.editItem(item1.itemUuid, modifiedItem1)
    TestCase.assertEquals(2, repository.getItemCount())

    // Retrieve
    val retrieved = repository.getItemById(item1.itemUuid)
    TestCase.assertEquals(50.0, retrieved.price)

    // Add more
    repository.addItem(item3)
    repository.addItem(item4)
    TestCase.assertEquals(4, repository.getItemCount())

    // Delete
    repository.deleteItem(item2.itemUuid)
    TestCase.assertEquals(3, repository.getItemCount())

    // Verify remaining items
    val allItems = repository.getAllItems()
    TestCase.assertEquals(3, allItems.size)
    assert(allItems.contains(modifiedItem1))
    assert(!allItems.contains(item2))
    assert(allItems.contains(item3))
    assert(allItems.contains(item4))
  }

  @Test
  fun itemsAreIndependent() = runTest {
    repository.addItem(item1)
    val retrieved1 = repository.getItemById(item1.itemUuid)

    // Original should still be unchanged in repository
    val retrieved2 = repository.getItemById(item1.itemUuid)
    TestCase.assertEquals(item1.price, retrieved2.price)
    TestCase.assertEquals(0.0, retrieved2.price)
  }

  @Test
  fun emptyMaterialListIsHandledCorrectly() = runTest {
    repository.addItem(item1) // item1 has empty material list

    val retrieved = repository.getItemById(item1.itemUuid)
    TestCase.assertEquals(item1, retrieved)
    TestCase.assertEquals(0, retrieved.material.size)
    assert(retrieved.material.isEmpty())
  }

  @Test
  fun uriIsPreservedCorrectly() = runTest {
    val customUri = "content://media/external/images/123"
    val itemWithCustomUri = item1.copy(image = item1.image.copy(imageUrl = customUri))

    repository.addItem(itemWithCustomUri)

    val retrieved = repository.getItemById(itemWithCustomUri.itemUuid)
    TestCase.assertEquals(customUri, retrieved.image.imageUrl)
    // TestCase.assertEquals(customUri.toString(), retrieved.image.toString())
  }

  @Test
  fun getAssociatedItemsReturnsOnlyMatchingPostItems() = runTest {
    val post1 = "post-A"
    val post2 = "post-B"

    val itemA = item1.copy(itemUuid = "A", postUuids = listOf(post1))
    val itemB = item2.copy(itemUuid = "B", postUuids = listOf(post1))
    val itemC = item3.copy(itemUuid = "C", postUuids = listOf(post2))

    repository.addItem(itemA)
    repository.addItem(itemB)
    repository.addItem(itemC)

    val post1Items = repository.getAssociatedItems(post1)
    val post2Items = repository.getAssociatedItems(post2)
    val noItems = repository.getAssociatedItems("post-XYZ")

    TestCase.assertEquals(2, post1Items.size)
    TestCase.assertTrue(post1Items.all { it.postUuids.contains(post1) })

    TestCase.assertEquals(1, post2Items.size)
    TestCase.assertTrue(post2Items.all { it.postUuids.contains(post2) })

    TestCase.assertTrue(noItems.isEmpty())
  }

  @Test
  fun deletePostItemsRemovesAllItemsForSpecificPost() = runTest {
    val post1 = "delete-this"
    val post2 = "keep-this"

    val itemA = item1.copy(itemUuid = "A", postUuids = listOf(post1))
    val itemB = item2.copy(itemUuid = "B", postUuids = listOf(post1))
    val itemC = item3.copy(itemUuid = "C", postUuids = listOf(post2))

    repository.addItem(itemA)
    repository.addItem(itemB)
    repository.addItem(itemC)
    TestCase.assertEquals(3, repository.getItemCount())

    repository.deletePostItems(post1)

    val remaining = repository.getAllItems()
    TestCase.assertEquals(1, remaining.size)
    TestCase.assertTrue(remaining.all { it.postUuids.contains(post2) })
    TestCase.assertTrue(repository.hasItem("C"))
    TestCase.assertFalse(repository.hasItem("A"))
    TestCase.assertFalse(repository.hasItem("B"))
  }

  @Test
  fun deletePostItemsDoesNothingWhenNoMatchFound() = runTest {
    val post1 = "existing-post"
    repository.addItem(item1.copy(postUuids = listOf(post1)))
    TestCase.assertEquals(1, repository.getItemCount())

    repository.deletePostItems("non-existent-post")
    TestCase.assertEquals(1, repository.getItemCount())
    TestCase.assertTrue(repository.hasItem(item1.itemUuid))
  }

  @Test
  fun getFriendItemsForPostReturnsEmptyWhenNoMatch() = runTest {
    val postUuid = "post-with-no-friend-items"
    val friendId = "friend-user-789"

    // Add items for current user only
    repository.addItem(item1.copy(postUuids = listOf(postUuid), ownerId = "user-123"))

    val friendItems = repository.getFriendItemsForPost(postUuid, friendId)

    TestCase.assertTrue(friendItems.isEmpty())
  }

  @Test
  fun getFriendItemsForPostFiltersCorrectlyByPostUuid() = runTest {
    val postUuid1 = "friend-post-aaa"
    val postUuid2 = "friend-post-bbb"
    val friendId = "friend-999"

    // Friend items for post1
    val friendItem1 =
        item1.copy(itemUuid = "friend-item-1", postUuids = listOf(postUuid1), ownerId = friendId)
    val friendItem2 =
        item2.copy(itemUuid = "friend-item-2", postUuids = listOf(postUuid1), ownerId = friendId)

    // Friend items for post2
    val friendItem3 =
        item3.copy(itemUuid = "friend-item-3", postUuids = listOf(postUuid2), ownerId = friendId)

    repository.addItem(friendItem1)
    repository.addItem(friendItem2)
    repository.addItem(friendItem3)

    // Get items for post1
    val itemsForPost1 = repository.getFriendItemsForPost(postUuid1, friendId)
    TestCase.assertEquals(2, itemsForPost1.size)
    TestCase.assertTrue(itemsForPost1.all { it.postUuids.contains(postUuid1) })
    TestCase.assertTrue(itemsForPost1.any { it.itemUuid == "friend-item-1" })
    TestCase.assertTrue(itemsForPost1.any { it.itemUuid == "friend-item-2" })

    // Get items for post2
    val itemsForPost2 = repository.getFriendItemsForPost(postUuid2, friendId)
    TestCase.assertEquals(1, itemsForPost2.size)
    TestCase.assertTrue(itemsForPost2.all { it.postUuids.contains(postUuid2) })
    TestCase.assertEquals("friend-item-3", itemsForPost2.first().itemUuid)
  }

  @Test
  fun getFriendItemsForPostWithMixedOwnersAndPosts() = runTest {
    val postUuid = "mixed-post"
    val friendId = "target-friend"

    // Target: friend's item for the post
    val targetItem =
        item1.copy(itemUuid = "target", postUuids = listOf(postUuid), ownerId = friendId)

    // Wrong post, correct friend
    val wrongPostItem =
        item2.copy(itemUuid = "wrong-post", postUuids = listOf("other-post"), ownerId = friendId)

    // Correct post, wrong friend
    val wrongFriendItem =
        item3.copy(
            itemUuid = "wrong-friend", postUuids = listOf(postUuid), ownerId = "other-friend")

    // Wrong post and friend
    val wrongBothItem =
        item4.copy(
            itemUuid = "wrong-both", postUuids = listOf("other-post"), ownerId = "other-friend")

    repository.addItem(targetItem)
    repository.addItem(wrongPostItem)
    repository.addItem(wrongFriendItem)
    repository.addItem(wrongBothItem)

    val friendItems = repository.getFriendItemsForPost(postUuid, friendId)

    // Should only return the target item
    TestCase.assertEquals(1, friendItems.size)
    TestCase.assertEquals("target", friendItems.first().itemUuid)
    TestCase.assertEquals(postUuid, friendItems.first().postUuids.first())
    TestCase.assertEquals(friendId, friendItems.first().ownerId)
  }

  @Test
  fun getItemsByIdsReturnsCorrectItems() = runTest {
    // Add multiple items
    repository.addItem(item1)
    repository.addItem(item2)
    repository.addItem(item3)
    repository.addItem(item4)

    // Test retrieving multiple items by their IDs
    val requestedIds = listOf(item1.itemUuid, item3.itemUuid, item4.itemUuid)
    val retrievedItems = repository.getItemsByIds(requestedIds)

    TestCase.assertEquals(3, retrievedItems.size)
    TestCase.assertTrue(retrievedItems.contains(item1))
    TestCase.assertTrue(retrievedItems.contains(item3))
    TestCase.assertTrue(retrievedItems.contains(item4))
    TestCase.assertFalse(retrievedItems.contains(item2))

    // Test with empty list
    val emptyResult = repository.getItemsByIds(emptyList())
    TestCase.assertTrue(emptyResult.isEmpty())

    // Test with non-existent IDs (should be filtered out)
    val mixedIds = listOf(item1.itemUuid, "non-existent-1", item2.itemUuid, "non-existent-2")
    val mixedResult = repository.getItemsByIds(mixedIds)
    TestCase.assertEquals(2, mixedResult.size)
    TestCase.assertTrue(mixedResult.contains(item1))
    TestCase.assertTrue(mixedResult.contains(item2))

    // Test with all non-existent IDs
    val nonExistentIds = listOf("fake-1", "fake-2", "fake-3")
    val nonExistentResult = repository.getItemsByIds(nonExistentIds)
    TestCase.assertTrue(nonExistentResult.isEmpty())

    // Test with single ID
    val singleResult = repository.getItemsByIds(listOf(item2.itemUuid))
    TestCase.assertEquals(1, singleResult.size)
    TestCase.assertEquals(item2, singleResult.first())

    // Test with duplicate IDs (should return item multiple times)
    val duplicateIds = listOf(item1.itemUuid, item1.itemUuid, item1.itemUuid)
    val duplicateResult = repository.getItemsByIds(duplicateIds)
    TestCase.assertEquals(3, duplicateResult.size) // mapNotNull keeps duplicates
    TestCase.assertTrue(duplicateResult.all { it == item1 })
  }

  @Test
  fun getItemsByIdsAcrossOwnersReturnsItems() = runTest {
    val friendItem = item2.copy(ownerId = "friend-user")
    repository.addItem(item1)
    repository.addItem(friendItem)

    val result = repository.getItemsByIdsAcrossOwners(listOf(item1.itemUuid, friendItem.itemUuid))

    TestCase.assertEquals(2, result.size)
    TestCase.assertTrue(result.contains(item1))
    TestCase.assertTrue(result.contains(friendItem))
  }

  @After
  fun tearDown() {
    repository.clearAll()
  }
}
