package com.android.ootd.ui.post

import android.content.Context
import android.net.Uri
import androidx.test.core.app.ApplicationProvider
import com.android.ootd.model.account.AccountRepository
import com.android.ootd.model.items.FirebaseImageUploader
import com.android.ootd.model.items.ImageData
import com.android.ootd.model.items.Item
import com.android.ootd.model.items.ItemsRepository
import com.android.ootd.model.items.Material
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.every
import io.mockk.mockk
import io.mockk.mockkObject
import junit.framework.TestCase.assertNotNull
import kotlin.collections.emptyList
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.test.StandardTestDispatcher
import kotlinx.coroutines.test.advanceUntilIdle
import kotlinx.coroutines.test.resetMain
import kotlinx.coroutines.test.runTest
import kotlinx.coroutines.test.setMain
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

// Test partially generated by the AI coding agent: Claude Sonnet 4.5
@OptIn(ExperimentalCoroutinesApi::class)
@RunWith(RobolectricTestRunner::class)
class EditItemsViewModelTest {

  private lateinit var viewModel: EditItemsViewModel
  private lateinit var mockRepository: ItemsRepository
  private lateinit var mockAccountRepository: AccountRepository
  private val testDispatcher = StandardTestDispatcher()

  @Before
  fun setup() {
    Dispatchers.setMain(testDispatcher)
    mockRepository = mockk(relaxed = true)
    mockAccountRepository = mockk(relaxed = true)
    viewModel = EditItemsViewModel(mockRepository, mockAccountRepository)
  }

  @After
  fun tearDown() {
    Dispatchers.resetMain()
  }

  @Test
  fun `initial state is correct`() {
    val state = viewModel.uiState.value
    assertEquals("", state.itemId)
    assertEquals(ImageData("", ""), state.image)
    assertNull(state.localPhotoUri)
    assertEquals("", state.category)
    assertEquals("", state.type)
    assertEquals("", state.brand)
    assertEquals(0.0, state.price, 0.0)
    assertEquals(emptyList<Material>(), state.material)
    assertEquals("", state.materialText)
    assertEquals("", state.link)
    assertNull(state.errorMessage)
    assertNull(state.invalidPhotoMsg)
    assertNull(state.invalidCategory)
    assertEquals(emptyList<String>(), state.suggestions)
    assertFalse(state.isSaveSuccessful)
  }

  @Test
  fun `isEditValid returns true when all required fields are valid`() = runTest {
    val mockUri = mockk<Uri>()
    every { mockUri.toString() } returns "content://test"

    viewModel.setPhoto(mockUri)
    viewModel.setCategory("Clothing")

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertTrue(state.isEditValid)
  }

  @Test
  fun `isEditValid returns false when image is empty`() {
    viewModel.setCategory("Clothing")

    val state = viewModel.uiState.value
    assertFalse(state.isEditValid)
  }

  @Test
  fun `isEditValid returns false when category is empty`() {
    val mockUri = mockk<Uri>()
    every { mockUri.toString() } returns "content://test"
    viewModel.setPhoto(mockUri)

    val state = viewModel.uiState.value
    assertFalse(state.isEditValid)
  }

  @Test
  fun `setPhoto updates localPhotoUri in state`() = runTest {
    val mockUri = mockk<Uri>()
    every { mockUri.toString() } returns "content://test"

    viewModel.setPhoto(mockUri)

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertEquals(mockUri, state.localPhotoUri)
    assertEquals(ImageData("", ""), state.image)
    assertNull(state.invalidPhotoMsg)
  }

  @Test
  fun `setPhoto with Uri EMPTY sets error message`() = runTest {
    viewModel.setPhoto(Uri.EMPTY)

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertNull(state.localPhotoUri)
    assertEquals(ImageData("", ""), state.image)
    assertEquals("Please select a photo.", state.invalidPhotoMsg)
  }

  @Test
  fun `setCategory updates category in state`() {
    viewModel.setCategory("Clothing")

    val state = viewModel.uiState.value
    assertEquals("Clothing", state.category)
    assertNull(state.invalidCategory)
  }

  @Test
  fun `setCategory with empty string sets error message`() {
    viewModel.setCategory("")

    val state = viewModel.uiState.value
    assertEquals("", state.category)
    assertEquals("Please select a category.", state.invalidCategory)
  }

  @Test
  fun `setType updates type in state`() {
    viewModel.setType("T-shirt")

    val state = viewModel.uiState.value
    assertEquals("T-shirt", state.type)
  }

  @Test
  fun `setBrand updates brand in state`() {
    viewModel.setBrand("Nike")

    val state = viewModel.uiState.value
    assertEquals("Nike", state.brand)
  }

  @Test
  fun `setPrice updates price in state`() {
    viewModel.setPrice(49.99)

    val state = viewModel.uiState.value
    assertEquals(49.99, state.price, 0.0)
  }

  @Test
  fun `setMaterial updates material in state`() {
    viewModel.setMaterial("Cotton 80%, Wool 20%")

    val state = viewModel.uiState.value
    assertEquals("Cotton 80%, Wool 20%", state.materialText)
    assertEquals(2, state.material.size)
    assertEquals("Cotton", state.material[0].name)
    assertEquals(80.0, state.material[0].percentage, 0.0)
    assertEquals("Wool", state.material[1].name)
    assertEquals(20.0, state.material[1].percentage, 0.0)
  }

  @Test
  fun `setMaterial handles single material`() {
    viewModel.setMaterial("Cotton 100%")

    val state = viewModel.uiState.value
    assertEquals("Cotton 100%", state.materialText)
    assertEquals(1, state.material.size)
    assertEquals("Cotton", state.material[0].name)
    assertEquals(100.0, state.material[0].percentage, 0.0)
  }

  @Test
  fun `setMaterial handles invalid format`() {
    viewModel.setMaterial("Invalid Format")

    val state = viewModel.uiState.value
    assertEquals("Invalid Format", state.materialText)
    assertEquals(0, state.material.size)
  }

  @Test
  fun `setMaterial handles empty string`() {
    viewModel.setMaterial("")

    val state = viewModel.uiState.value
    assertEquals("", state.materialText)
    assertEquals(0, state.material.size)
  }

  @Test
  fun `setLink updates link in state`() {
    viewModel.setLink("https://example.com")

    val state = viewModel.uiState.value
    assertEquals("https://example.com", state.link)
  }

  @Test
  fun `setErrorMsg updates error message`() {
    viewModel.setErrorMsg("Test error")

    val state = viewModel.uiState.value
    assertEquals("Test error", state.errorMessage)
  }

  @Test
  fun `clearErrorMsg clears error message`() {
    viewModel.setErrorMsg("Test error")
    viewModel.clearErrorMsg()

    val state = viewModel.uiState.value
    assertNull(state.errorMessage)
  }

  @Test
  fun `loadItem populates state with item data`() {
    val materials = listOf(Material("Cotton", 100.0))
    val item =
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = "T-shirt",
            brand = "Nike",
            price = 49.99,
            material = materials,
            link = "https://example.com",
            ownerId = "ownerId")

    viewModel.loadItem(item)

    val state = viewModel.uiState.value
    assertEquals("test-id", state.itemId)
    assertEquals(ImageData("test-image-id", "https://example.com/test.jpg"), state.image)
    assertEquals("Clothing", state.category)
    assertEquals("T-shirt", state.type)
    assertEquals("Nike", state.brand)
    assertEquals(49.99, state.price, 0.0)
    assertEquals(materials, state.material)
    assertEquals("Cotton 100.0%", state.materialText)
    assertEquals("https://example.com", state.link)
  }

  @Test
  fun `loadItem handles null optional values`() {
    val item =
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = null,
            brand = null,
            price = null,
            material = emptyList(),
            link = null,
            ownerId = "ownerId")

    viewModel.loadItem(item)

    val state = viewModel.uiState.value
    assertEquals("test-id", state.itemId)
    assertEquals(ImageData("test-image-id", "https://example.com/test.jpg"), state.image)
    assertEquals("Clothing", state.category)
    assertEquals("", state.type)
    assertEquals("", state.brand)
    assertEquals(0.0, state.price, 0.0)
    assertEquals("", state.materialText)
    assertEquals("", state.link)
  }

  @Test
  fun `onSaveItemClick sets error when validation fails`() = runTest {
    viewModel.onSaveItemClick()

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertEquals("Please fill in all required fields.", state.errorMessage)
    assertFalse(state.isSaveSuccessful)
  }

  @Test
  fun `onSaveItemClick sets error when URL is invalid`() = runTest {
    val mockUri = mockk<Uri>()
    every { mockUri.toString() } returns "content://test"

    viewModel.setPhoto(mockUri)
    viewModel.setCategory("Clothing")
    viewModel.setLink("invalid-url")

    viewModel.onSaveItemClick()

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertEquals("Please enter a valid URL.", state.errorMessage)
  }

  @Test
  fun `onSaveItemClick returns true and calls repository when valid`() = runTest {
    val mockUri = mockk<Uri>()
    every { mockUri.toString() } returns "content://test"

    coEvery { mockRepository.editItem(any(), any()) } returns Unit

    // Load an item first to set itemId
    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = "T-shirt",
            brand = "Nike",
            price = 49.99,
            material = emptyList(),
            link = "https://example.com",
            ownerId = "ownerId"))

    viewModel.onSaveItemClick()
    advanceUntilIdle()

    coVerify { mockRepository.editItem("test-id", any()) }
    assertNull(viewModel.uiState.value.errorMessage)
    assertTrue(viewModel.uiState.value.isSaveSuccessful)
  }

  @Test
  fun `onSaveItemClick allows empty link`() = runTest {
    coEvery { mockRepository.editItem(any(), any()) } returns Unit

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = "T-shirt",
            brand = "Nike",
            price = 49.99,
            material = emptyList(),
            link = "",
            ownerId = "ownerId"))

    viewModel.onSaveItemClick()
    advanceUntilIdle()

    coVerify { mockRepository.editItem("test-id", any()) }
    assertNull(viewModel.uiState.value.errorMessage)
    assertTrue(viewModel.uiState.value.isSaveSuccessful)
  }

  @Test
  fun `onSaveItemClick handles exception`() = runTest {
    coEvery { mockRepository.editItem(any(), any()) } throws Exception("Update failed")

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = "T-shirt",
            brand = "Nike",
            price = 49.99,
            material = emptyList(),
            link = "https://example.com",
            ownerId = "ownerId"))

    viewModel.onSaveItemClick()

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertEquals("Failed to update item: Update failed", state.errorMessage)
  }

  @Test
  fun `deleteItem calls repository when itemId is not empty`() = runTest {
    mockkObject(FirebaseImageUploader)
    coEvery { FirebaseImageUploader.deleteImage(any()) } returns true
    coEvery { mockAccountRepository.removeItem(any()) } returns true

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = null,
            brand = null,
            price = null,
            material = emptyList(),
            link = null,
            ownerId = "ownerId"))
    viewModel.deleteItem()

    advanceUntilIdle()

    coVerify { mockRepository.deleteItem("test-id") }
    coVerify { mockAccountRepository.removeItem("test-id") }
    val state = viewModel.uiState.value
    assertTrue(state.isDeleteSuccessful)
    assertNull(state.errorMessage)
  }

  @Test
  fun `deleteItem does not call repository when itemId is empty`() = runTest {
    viewModel.deleteItem()

    advanceUntilIdle()

    coVerify(exactly = 0) { mockRepository.deleteItem(any()) }
    val state = viewModel.uiState.value
    assertEquals("No item to delete.", state.errorMessage)
  }

  @Test
  fun `deleteItem handles exception`() = runTest {
    coEvery { mockAccountRepository.removeItem(any()) } returns true
    coEvery { mockRepository.deleteItem(any()) } throws Exception("Delete failed")

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = null,
            brand = null,
            price = null,
            material = emptyList(),
            link = null,
            ownerId = "ownerId"))
    viewModel.deleteItem()

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertEquals("Failed to delete item: Delete failed", state.errorMessage)
    assertFalse(state.isDeleteSuccessful)
    assertNotNull(state.errorMessage)
  }

  @Test
  fun `deleteItem fails when removing from inventory fails`() = runTest {
    coEvery { mockAccountRepository.removeItem(any()) } returns false

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = null,
            brand = null,
            price = null,
            material = emptyList(),
            link = null,
            ownerId = "ownerId"))

    viewModel.deleteItem()

    advanceUntilIdle()

    // Verify the operation failed and didn't proceed to delete the item
    val state = viewModel.uiState.value
    assertEquals("Failed to remove item from inventory. Please try again.", state.errorMessage)
    assertFalse(state.isDeleteSuccessful)
    coVerify(exactly = 0) { mockRepository.deleteItem(any()) }
  }

  @Test
  fun `deleteItem logs warning when image deletion fails`() = runTest {
    mockkObject(FirebaseImageUploader)

    // Mock successful repository deletion but failed image deletion
    coEvery { mockRepository.deleteItem(any()) } returns Unit
    coEvery { mockAccountRepository.removeItem(any()) } returns true
    coEvery { FirebaseImageUploader.deleteImage(any()) } returns false

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("test-image-id", "https://example.com/test.jpg"),
            category = "Clothing",
            type = null,
            brand = null,
            price = null,
            material = emptyList(),
            link = null,
            ownerId = "ownerId"))

    viewModel.deleteItem()

    advanceUntilIdle()

    // Verify the item deletion was successful despite image deletion failure
    val state = viewModel.uiState.value
    assertTrue(state.isDeleteSuccessful)
    assertNull(state.errorMessage)

    // Verify image deletion was attempted
    coVerify { FirebaseImageUploader.deleteImage("test-image-id") }
  }

  @Test
  fun `initTypeSuggestions loads suggestions from context`() {
    val context = ApplicationProvider.getApplicationContext<Context>()

    viewModel.initTypeSuggestions(context)

    // After initialization, suggestions should be available
    viewModel.setCategory("Clothing")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isNotEmpty())
  }

  @Test
  fun `updateTypeSuggestions filters by input`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Clothing")
    viewModel.updateTypeSuggestions("T")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.all { it.startsWith("T", ignoreCase = true) })
  }

  @Test
  fun `updateTypeSuggestions returns all suggestions when input is blank`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Clothing")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isNotEmpty())
  }

  @Test
  fun `updateTypeSuggestions works with valid category - Clothing`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Clothing")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isNotEmpty())
  }

  @Test
  fun `updateTypeSuggestions works with valid category - Shoes`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Shoes")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isNotEmpty())
  }

  @Test
  fun `updateTypeSuggestions works with valid category - Bags`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Bags")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isNotEmpty())
  }

  @Test
  fun `updateTypeSuggestions works with valid category - Accessories`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Accessories")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isNotEmpty())
  }

  @Test
  fun `updateTypeSuggestions returns empty list for invalid category`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("InvalidCategory")
    viewModel.updateTypeSuggestions("")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.isEmpty())
  }

  @Test
  fun `updateTypeSuggestions filters case insensitive`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    viewModel.setCategory("Clothing")
    viewModel.updateTypeSuggestions("t-shirt")

    val state = viewModel.uiState.value
    assertTrue(state.suggestions.any { it.equals("T-shirt", ignoreCase = true) })
  }

  @Test
  fun `updateCategorySuggestions does not modify state in EditItemsViewModel`() {
    val context = ApplicationProvider.getApplicationContext<Context>()
    viewModel.initTypeSuggestions(context)

    val initialState = viewModel.uiState.value
    viewModel.updateCategorySuggestions("Cloth")

    val finalState = viewModel.uiState.value
    // In EditItemsViewModel, updateCategorySuggestionsState returns state unchanged
    assertEquals(initialState.suggestions, finalState.suggestions)
  }

  @Test
  fun `onSaveItemClick sets error when image upload fails`() = runTest {
    mockkObject(FirebaseImageUploader)
    val mockUri = mockk<Uri>()
    every { mockUri.toString() } returns "content://test"

    // Mock image upload to return empty URL (failure case)
    coEvery { FirebaseImageUploader.uploadImage(any(), any()) } returns ImageData("test-id", "")

    viewModel.loadItem(
        Item(
            itemUuid = "test-id",
            postUuids = listOf("test_post_uuid"),
            image = ImageData("", ""),
            category = "Clothing",
            type = "T-shirt",
            brand = "Nike",
            price = 49.99,
            material = emptyList(),
            link = "https://example.com",
            ownerId = "ownerId"))

    viewModel.setPhoto(mockUri)
    viewModel.onSaveItemClick()

    advanceUntilIdle()

    val state = viewModel.uiState.value
    assertEquals("Please select a photo.", state.errorMessage)
    assertFalse(state.isSaveSuccessful)
    coVerify(exactly = 0) { mockRepository.editItem(any(), any()) }
  }
}
