package com.android.ootd.ui.post

import android.net.Uri
import androidx.compose.ui.test.assertCountEquals
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onAllNodesWithTag
import androidx.compose.ui.test.onNodeWithTag
import androidx.compose.ui.test.performClick
import androidx.compose.ui.test.performTextInput
import androidx.compose.ui.test.performTextReplacement
import org.junit.Before
import org.junit.Rule
import org.junit.Test

// DISCLAIMER: The following tests were partly generated by AI and verified by human.

/**
 * Tests for FitCheckScreen UI behavior.
 *
 * Covers description character limit, dialog behavior, error display, and ViewModel interactions.
 * These tests ensure that user-facing interactions in the FitCheckScreen behave as expected.
 */
class FitCheckScreenTest {

  @get:Rule val composeTestRule = createComposeRule()

  private lateinit var viewModel: FitCheckViewModel

  @Before
  fun setUp() {
    viewModel = FitCheckViewModel()
    composeTestRule.setContent { FitCheckScreen(fitCheckViewModel = viewModel) }
  }

  @Test
  fun fitCheckScreen_showsPlaceholder_andAddPhotoButton() {
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.PLACEHOLDER_ICON).assertIsDisplayed()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.ADD_PHOTO_BUTTON).assertIsDisplayed()
  }

  @Test
  fun descriptionAndCounter_areVisibleOnScreen() {
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.DESCRIPTION_INPUT).assertIsDisplayed()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.DESCRIPTION_COUNTER).assertIsDisplayed()
  }

  @Test
  fun clickingAddPhotoButton_opensDialog() {
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.ADD_PHOTO_BUTTON).performClick()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.ALERT_DIALOG).assertIsDisplayed()
  }

  @Test
  fun dialog_containsCameraAndGalleryButtons() {
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.ADD_PHOTO_BUTTON).performClick()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.TAKE_PHOTO_BUTTON).assertIsDisplayed()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.CHOOSE_GALLERY_BUTTON).assertIsDisplayed()
  }

  @Test
  fun clickingChooseFromGallery_dismissesDialog() {
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.ADD_PHOTO_BUTTON).performClick()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.CHOOSE_GALLERY_BUTTON).performClick()
    composeTestRule.waitForIdle()

    composeTestRule.onAllNodesWithTag(FitCheckScreenTestTags.ALERT_DIALOG).assertCountEquals(0)
  }

  @Test
  fun clickingAddPhotoButton_thenTakePhoto_closesDialogAndKeepsInvalidState() {
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.ADD_PHOTO_BUTTON).performClick()
    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.TAKE_PHOTO_BUTTON).performClick()
    composeTestRule.waitForIdle()

    // Dialog gone, still invalid because no actual photo set
    composeTestRule.onAllNodesWithTag(FitCheckScreenTestTags.ALERT_DIALOG).assertCountEquals(0)
    composeTestRule.runOnIdle { assert(!viewModel.uiState.value.isPhotoValid) }
  }

  @Test
  fun setPhoto_updatesViewModelAndShowsPreview() {
    val uri = Uri.parse("content://dummy/photo.jpg")

    composeTestRule.runOnIdle { viewModel.setPhoto(uri) }
    composeTestRule.waitForIdle()

    composeTestRule.runOnIdle {
      assert(viewModel.uiState.value.image == uri)
      assert(viewModel.uiState.value.isPhotoValid)
    }

    composeTestRule.onNodeWithTag(FitCheckScreenTestTags.IMAGE_PREVIEW).assertExists()
  }

  @Test
  fun description_overLimit_isIgnored() {
    val inputField = composeTestRule.onNodeWithTag(FitCheckScreenTestTags.DESCRIPTION_INPUT)
    val validText = "x".repeat(100)
    val tooLongText = "x".repeat(150)

    inputField.performTextInput(validText)
    composeTestRule.waitForIdle()

    composeTestRule.runOnIdle { assert(viewModel.uiState.value.description.length == 100) }

    inputField.performTextReplacement(tooLongText)
    composeTestRule.waitForIdle()

    composeTestRule.runOnIdle {
      val actualLength = viewModel.uiState.value.description.length
      assert(actualLength == 100) { "Expected capped at 100, but got $actualLength" }
    }
  }
}
